/**
* web5 SDK test server
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.web5.models


/**
 * 
 * @param `const` 
 * @param `enum` 
 * @param exclusiveMinimum 
 * @param exclusiveMaximum 
 * @param format 
 * @param formatMaximum 
 * @param formatMinimum 
 * @param formatExclusiveMaximum 
 * @param formatExclusiveMinimum 
 * @param minLength 
 * @param maxLength 
 * @param minimum 
 * @param maximum 
 * @param pattern 
 * @param type 
 */
data class PresentationDefinitionFilter(
    val `const`: kotlin.String? = null,
    val `enum`: kotlin.collections.List<kotlin.String>? = null,
    val exclusiveMinimum: kotlin.String? = null,
    val exclusiveMaximum: kotlin.String? = null,
    val format: kotlin.String? = null,
    val formatMaximum: kotlin.String? = null,
    val formatMinimum: kotlin.String? = null,
    val formatExclusiveMaximum: kotlin.String? = null,
    val formatExclusiveMinimum: kotlin.String? = null,
    val minLength: java.math.BigDecimal? = null,
    val maxLength: java.math.BigDecimal? = null,
    val minimum: kotlin.String? = null,
    val maximum: kotlin.String? = null,
    val pattern: kotlin.String? = null,
    val type: kotlin.String? = null
) 

