/**
* web5 SDK test server
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.web5.models


/**
 * 
 * @param limitDisclosure 
 * @param statuses 
 * @param fields 
 * @param subjectIsIssuer 
 * @param isHolder 
 * @param sameSubject 
 */
data class PresentationDefinitionConstraints(
    val limitDisclosure: PresentationDefinitionConstraints.LimitDisclosure? = null,
    val statuses: PresentationDefinitionStatuses? = null,
    val fields: kotlin.collections.List<PresentationDefinitionField>? = null,
    val subjectIsIssuer: PresentationDefinitionConstraints.SubjectIsIssuer? = null,
    val isHolder: kotlin.collections.List<PresentationDefinitionHolderSubject>? = null,
    val sameSubject: kotlin.collections.List<PresentationDefinitionHolderSubject>? = null
) 
{
    /**
    * 
    * Values: required,preferred
    */
    enum class LimitDisclosure(val value: kotlin.String){
        required("required"),
        preferred("preferred");
    }
    /**
    * 
    * Values: required,preferred
    */
    enum class SubjectIsIssuer(val value: kotlin.String){
        required("required"),
        preferred("preferred");
    }
}

