/**
* web5 SDK test server
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package models

import models.CredentialIssuer
import models.CredentialProof

/**
 * 
 * @param atContext 
 * @param id 
 * @param type 
 * @param issuer 
 * @param issuanceDate 
 * @param expirationDate 
 * @param credentialSubject 
 * @param proof 
 */
data class VerifiableCredential(
    val atContext: kotlin.collections.List<kotlin.String>,
    val id: kotlin.String,
    val type: kotlin.collections.List<kotlin.String>,
    val issuer: CredentialIssuer,
    val issuanceDate: kotlin.String,
    val expirationDate: kotlin.String,
    val credentialSubject: kotlin.collections.Map<kotlin.String, kotlin.Any>,
    val proof: CredentialProof
) 

