/**
* web5 SDK test server
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.web5.models


/**
 * 
 * @param rule 
 * @param name 
 * @param purpose 
 * @param count 
 * @param min 
 * @param max 
 * @param from 
 * @param fromNested 
 */
data class PresentationDefinitionSubmissionRequirement(
    val rule: PresentationDefinitionSubmissionRequirement.Rule,
    val name: kotlin.String? = null,
    val purpose: kotlin.String? = null,
    val count: java.math.BigDecimal? = null,
    val min: java.math.BigDecimal? = null,
    val max: java.math.BigDecimal? = null,
    val from: kotlin.String? = null,
    val fromNested: kotlin.collections.List<PresentationDefinitionSubmissionRequirement>? = null
) 
{
    /**
    * 
    * Values: all,pick
    */
    enum class Rule(val value: kotlin.String){
        all("all"),
        pick("pick");
    }
}

