/**
* web5 SDK test server
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.web5.models


/**
 * 
 * @param id 
 * @param name 
 * @param purpose 
 * @param group 
 * @param issuance 
 * @param constraints 
 */
data class PresentationDefinitionInputDescriptor(
    val id: kotlin.String,
    val name: kotlin.String? = null,
    val purpose: kotlin.String? = null,
    val group: kotlin.collections.List<kotlin.String>? = null,
    val issuance: kotlin.collections.List<PresentationDefinitionIssuance>? = null,
    val constraints: PresentationDefinitionConstraints? = null
) 

